{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "86242667-11c7-4cf4-9fe5-483e5199aa68",
   "metadata": {},
   "source": [
    "# Assignment - 9"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "72a32263-ba1e-4da5-b4c5-0f62a819d7d0",
   "metadata": {},
   "source": [
    "#### Q1.Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "##### Note: Here Exception class refers to the base class for all the exceptions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3d2dd24a-2a01-4813-9160-9f8076904697",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "When creating custom exceptions in a programming language like Java, Python, or C#, it's important to use the \n",
    "Exception class (or a similar base class, depending on the language) as the base class for your custom exception. \n",
    "This is because the Exception class provides a foundational structure and functionality that is essential for \n",
    "proper error handling and exception management. Here are some reasons why you should use the Exception class \n",
    "when creating custom exceptions:\n",
    "1. Standardization: Using the Exception class ensures that your custom exception follows the standard exception \n",
    "hierarchy and design patterns of the programming language. This makes it easier for other developers to understand \n",
    "and work with your custom exception, as they are already familiar with the conventions and behavior of the base \n",
    "Exception class.\n",
    "2.Consistency: By inheriting from the Exception class, you benefit from the consistent handling of exceptions across \n",
    "your codebase. Exception classes are usually caught and handled in a uniform way, making it easier to manage and \n",
    "respond to errors in a consistent manner.\n",
    "3. Exception handling: Exception classes often include important methods and properties, such as getMessage() or \n",
    "toString(), that provide valuable information about the exception. Inheriting from the Exception class allows you to \n",
    "leverage these methods to provide meaningful error messages and details when an exception is thrown.\n",
    "4. Exception chaining: In some programming languages, Exception classes support exception chaining. This means that you \n",
    "can catch one exception and throw another while preserving the original exception's context. Exception chaining helps in \n",
    "debugging and understanding the flow of errors in your code. If you create custom exceptions using the Exception class, \n",
    "you can take advantage of this feature.\n",
    "5. Customization: While inheriting from the Exception class, you can add custom properties and methods to your custom \n",
    "exception, making it specific to your application's needs. This allows you to extend the basic Exception class to include \n",
    "additional information or behavior that is relevant to your use case.\n",
    "6. Compatibility: When you use the Exception class as the base class, your custom exceptions can seamlessly integrate with \n",
    "existing exception handling mechanisms in libraries, frameworks, and other parts of your codebase. This ensures that your \n",
    "custom exceptions work well in the broader context of your application.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e9cc0ee-2a59-40df-af59-c2827f646f0c",
   "metadata": {},
   "source": [
    "#### Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0e268d80-d1dc-4e2c-839f-9cb5227ddbdb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "  BaseExceptionGroup\n",
      "    ExceptionGroup\n",
      "  Exception\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    AssertionError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    BufferError\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "        PackageNotFoundError\n",
      "      ZipImportError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    MemoryError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    OSError\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    ReferenceError\n",
      "    RuntimeError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      RecursionError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      BrokenBarrierError\n",
      "      VariableError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      AddressValueError\n",
      "      NetmaskValueError\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MacroToEdit\n",
      "      InvalidVersion\n",
      "    Warning\n",
      "      BytesWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      EncodingWarning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      PendingDeprecationWarning\n",
      "      ResourceWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "      SyntaxWarning\n",
      "      UnicodeWarning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "    ExceptionGroup\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    Error\n",
      "    error\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    Error\n",
      "      CancelledError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    Incomplete\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    TraitError\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    COMError\n",
      "    ReturnValueIgnoredError\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    InvalidPortNumber\n",
      "    NoIPAddresses\n",
      "    Error\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    KnownIssue\n",
      "    VerifierFailure\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    GuardRejection\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    Error\n",
      "    TimeoutExpired\n",
      "    TimeoutAbandoned\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "  GeneratorExit\n",
      "  KeyboardInterrupt\n",
      "  SystemExit\n",
      "  CancelledError\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, level=0):\n",
    "    print('  ' * level + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, level + 1)\n",
    "\n",
    "print_exception_hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a4048acf-d452-49c3-8687-7acee239608a",
   "metadata": {},
   "source": [
    "#### Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "32b48903-3ad3-4bbe-998e-6daf374c6eca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "In Python, the ArithmeticError is a base class for various exceptions related to arithmetic operations. \n",
    "It is not meant to be directly raised; instead, it serves as a base class for more specific exceptions \n",
    "that are derived from it. Two commonly used exceptions derived from ArithmeticError are ZeroDivisionError \n",
    "and OverflowError. Let's explain these two exceptions with examples:\n",
    "\n",
    "1. ZeroDivisionError: - This exception is raised when you try to divide a number by zero, \n",
    "which is mathematically undefined.\n",
    "\n",
    "\n",
    "2.OverflowError: - This exception is raised when an arithmetic operation produces a result \n",
    "that exceeds the maximum representable value for a numeric type, such as an integer.\n",
    "\"\"\"\n",
    "\n",
    "dividend = 10\n",
    "divisor = 0\n",
    "\n",
    "try:\n",
    "    result = dividend / divisor\n",
    "except ZeroDivisionError as e:\n",
    "    print(f\"Error: {e}\")\n",
    "\n",
    "\n",
    "import sys\n",
    "\n",
    "try:\n",
    "    x = sys.maxsize\n",
    "    y = x + 1\n",
    "except OverflowError as e:\n",
    "    print(f\"Error: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "81cd6e58-16b8-47ff-ab22-cfc7e35076b7",
   "metadata": {},
   "source": [
    "#### Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3fbf8c40-f85a-4aab-bf7e-0c4cb1005727",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "KeyError: 'x'\n",
      "\n",
      "\n",
      "IndexError: list index out of range\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "LookupError is a base class for exceptions in Python that are raised when a key or index used \n",
    "to access a mapping or sequence is not found. This class is part of the Python exception hierarchy \n",
    "and serves as a parent class for more specific lookup-related exceptions like KeyError and IndexError.\n",
    "\"\"\"\n",
    "# 1. KeyError example\n",
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "try:\n",
    "    value = my_dict['x'] \n",
    "except KeyError as e:\n",
    "    print(f\"KeyError: {e}\")\n",
    "    print(\"\\n\")\n",
    "\n",
    "# 2. IndexError example\n",
    "my_list = [1, 2, 3, 4, 5]\n",
    "try:\n",
    "    value = my_list[10]  \n",
    "except IndexError as e:\n",
    "    print(f\"IndexError: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "981415e6-69ec-4a19-9aa6-0c94f752f918",
   "metadata": {},
   "source": [
    "#### Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0173a199-9ef6-440b-8b5d-d6f2c2b78edd",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "ImportError and ModuleNotFoundError are both exceptions in Python that occur when there is an \n",
    "issue with importing modules or packages. They are often encountered when you are trying to use\n",
    "a module or library that cannot be found or imported correctly. Let's look at each of them in detail:\n",
    "\n",
    "1.ImportError:\n",
    "ImportError is a general exception that is raised when there is a problem with importing a module. \n",
    "This can happen for various reasons, such as:-\n",
    "a. The module you are trying to import does not exist or is not in the Python standard library or your current \n",
    "    working directory.\n",
    "b. There might be an issue with the syntax or structure of the Python script that you are trying to import.\n",
    "c. The module you are trying to import relies on other modules that are not installed or have their own import \n",
    "    issues.\n",
    "\n",
    "2. ModuleNotFoundError:\n",
    "ModuleNotFoundError is a more specific exception introduced in Python 3.6. It is raised when Python cannot \n",
    "find the module or package you are trying to import. It is a subclass of ImportError and provides a more \n",
    "informative error message about the missing module or package.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a44aa424-6eba-48d7-b378-033767a5fed6",
   "metadata": {},
   "source": [
    "#### Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a11e3e1-cbf6-4857-a9ec-d5c19d271ca7",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Exception handling is a critical aspect of writing robust and maintainable Python code. \n",
    "Here are some best practices for exception handling in Python:-\n",
    "\n",
    "1. Use Specific Exceptions: Catch the most specific exception that you can handle. \n",
    "This allows you to handle different exceptions differently. For example, catch ValueError \n",
    "instead of a broad Exception if you're only interested in handling value-related errors.\n",
    "\n",
    "2.Avoid Bare Excepts: Avoid using a bare except: statement, as it can catch unexpected \n",
    "errors and make debugging difficult. Always specify the exceptions you expect to handle.\n",
    "\n",
    "3.Use try...except Blocks: Wrap the code that may raise an exception in a try...except block. \n",
    "This isolates the code that might fail from the rest of your program.\n",
    "\n",
    "4.Use try...except Blocks: Wrap the code that may raise an exception in a try...except block. \n",
    "This isolates the code that might fail from the rest of your program.\n",
    "\n",
    "5.Raising Exceptions: Raise exceptions when an error condition is encountered using the raise statement. \n",
    "This allows you to create custom exceptions for your application.\n",
    "\n",
    "6.Custom Exception Classes: Create custom exception classes by inheriting from the Exception class. \n",
    "This can help make your error messages more meaningful and provide more context.\n",
    "\n",
    "7.Handle Exceptions Locally: Handle exceptions as close to the source of the error as possible. \n",
    "Avoid handling exceptions too broadly at the top-level of your program.\n",
    "\n",
    "8.Logging: Use Python's logging module to log exception information. \n",
    "This can be invaluable for debugging and monitoring applications.\n",
    "\n",
    "9.Graceful Degradation: When dealing with external resources (e.g., files, databases, network connections), \n",
    "plan for graceful degradation. Handle exceptions gracefully by providing fallback behavior or notifying users.\n",
    "\n",
    "10.Comment Your Code: Add comments to explain why you are catching exceptions and what the intended behavior \n",
    "is when an exception occurs.\n",
    "\n",
    "11.Use Context Managers: Use context managers (e.g., with statements) for resources that need to be \n",
    "cleaned up automatically, like files and database connections. They ensure that resources are properly closed,\n",
    "even in the presence of exceptions.\n",
    "\n",
    "12.Avoid Silent Failures: Avoid allowing your program to continue silently after an exception has occurred. \n",
    "It's better to raise and handle exceptions properly or exit the program if necessary.\n",
    "\n",
    "13.Test Exception Handling: Write unit tests that cover exception handling scenarios to ensure that your \n",
    "code behaves as expected in the presence of exceptions.\n",
    "\n",
    "14.Avoid Overusing Exceptions: Exceptions should not be used for normal program flow control. \n",
    "They should be reserved for exceptional circumstances.\n",
    "\n",
    "15. Keep Exception Messages Descriptive: When raising exceptions or handling them, use informative and \n",
    "clear error messages to help with debugging and troubleshooting.\n",
    "\n",
    "16.Consider Using Third-Party Libraries: Depending on the complexity of your application, you might \n",
    "benefit from using third-party libraries like sentry or Rollbar for advanced error tracking and monitoring.\n",
    "\"\"\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
